<h3>Report Finding</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post" enctype="multipart/form-data">
    <fieldset>
        <div>
            Apakah anda yakin akan menghapus data ini?
        </div>
        <div class="fieldset-kiri">Tanggal Kejadian</div>
        <div class="fieldset-kanan"><?php echo $params['tanggalKejadian'] ?></div>
        <div class="fieldset-kiri">Kejadian</div>
        <div class="fieldset-kanan"><?php echo $params['kejadian'] ?></div>
        <div class="fieldset-kiri">Tindakan</div>
        <div class="fieldset-kanan"><?php echo $params['tindakan'] ?></div>
        <hr />
        <input type='submit' value='Batal' name='btx'>
        <input type='submit' value='Hapus' name='btx'>
    </fieldset>
</form>

<style type="text/css">
    .fieldset-kiri {
        width: 150px;
        float: left;
        margin-bottom: 5px;
        clear: left;
        vertical-align: top;
    }

    .fieldset-kanan {
        margin-left: 150px;
        margin-bottom: 5px;
        vertical-align: top;
    }

    .fieldset-kanan:before {
        content: ': ';
        vertical-align: top;
    }

    .fieldset-empty:before {
        content: ' ';
    }

    .fieldset-button {
        margin-left: 157px;
        margin-bottom: 5px;
    }

    .required:after {
        content: ' *';
        color: red;
    }

    .error-head {
        color: red;
        font-weight: bold;
    }

    .error-container {
        color: red;
        margin-left: 7px;
    }
</style>

<script type="text/javascript">
</script>
