<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
        <meta name="author" content="Gatot S" />
        <style type="text/css">
            body, .content {
                width: 100%;
                text-align: center;
            }

            table.centered {
                margin: 0 auto;
            }

            table.full-border {
                border-collapse: collapse;
                border: 1px solid #000000;
            }

            table.full-border th,
            table.full-border td {
                border: 1px solid #000000;
            }

            table.full-border td {
                text-align: left;
            }
        </style>
    </head>
    <body>
        <div id="head">
            <h3>
                PT. Woodworth Wooden Industries Indonesia<br />
                Online Reporting System
            </h3>
        </div>
        <div id="container">
            <div id="content">
                <h3>Report Finding</h3>
                <?php if ($data !== null) : ?>
                <table class='centered full-border'>
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th style='width: 80px;'>Tanggal</th>
                            <th style='width: 270px;'>Kejadian</th>
                            <th style='width: 270px;'>Tindakan</th>
                        </tr>
                    </thead>
                        <?php if (count($data) > 0) :
                            $number = 1; ?>
                    <tbody>
                        <?php foreach ($data as $row) :
                                $photos = $row->getFindingPhotos(); ?>
                        <tr>
                            <td<?php echo count($photos) > 0 ? ' rowspan=2' : ''; ?> style='vertical-align: top;'><?php echo $number++ ?></td>
                            <td<?php echo count($photos) > 0 ? ' rowspan=2' : ''; ?> style='vertical-align: top;'><?php echo $row->getTanggal()->format('d-M-Y') ?></td>
                            <td style='vertical-align: top;'><?php echo nl2br($row->getKejadian()) ?></td>
                            <td style='vertical-align: top;'><?php echo nl2br($row->getTindakan()) ?></td>
                            <?php if (count($photos) > 0) : ?>
                        </tr>
                        <tr>
                            <td colspan='2'>
                            <?php foreach ($photos as $photo) : ?>
                                <img src='./images/<?php
                                    echo $this->routeManager->getModule()
                                        . '/' . $this->routeManager->getController()
                                        . '/' . $photo->getNamaFile() ?>' width='100px' />
                            <?php endforeach; endif; ?>
                            </td>
                        </tr>
                        <?php endforeach;
                            else : ?>
                        <tr>
                            <td colspan='0' style='text-align: center;'>Data kosong</td>
                        </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
                <?php endif; ?>
            </div>
        </div>
    </body>
</html>
