<h3>Report Peripheral</h3>
<?php if (!empty($errorMessages)) : ?>
<ul>
    <?php foreach ($errorMessages as $errorMessage) : ?>
        <li><?php echo $errorMessage ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<form method='post'>
    <div>
        Apakah anda yakin akan menghapus data ini?
    </div>
    <table class='detail' border='0' width='100%'>
        <tbody>
            <tr>
                <td>Nama</td>
                <td><?php echo $data->getNama() ?></td>
            </tr>
            <tr>
                <td>Nomor Seri</td>
                <td><?php echo $data->getNomorSeri() ?></td>
            </tr>
            <tr>
                <td>Brand</td>
                <td><?php echo $data->getBrand() ?></td>
            </tr>
            <tr>
                <td>Type</td>
                <td><?php echo $data->getType() ?></td>
            </tr>
            <tr>
                <td>Port</td>
                <td><?php echo $data->getPort() ?></td>
            </tr>
            <tr>
                <td>Lokasi</td>
                <td><?php echo $data->getLokasi() ?></td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type='submit' value='Delete' name='btx' />
    <input type='submit' value='Cancel' name='btx' />
</form>

<style type='text/css'>
    table.detail tbody tr td:first-child {
        width: 150px;
    }
</style>
