<h3>Report Peripheral</h3>
<?php if (!empty($errorMessages)) : ?>
<ul>
    <?php foreach ($errorMessages as $errorMessage) : ?>
        <li><?php echo $errorMessage ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<form action='' method='post'>
    <table border='0' width='100%'>
        <tbody>
            <tr>
                <td>Nama</td>
                <td><input type='text' size='30' name='nama' value='<?php echo $params['nama'] ?>' /></td>
            </tr>
            <tr>
                <td>Nomor Seri</td>
                <td><input type='text' size='50' name='nomorSeri' value='<?php echo $params['nomorSeri'] ?>' /></td>
            </tr>
            <tr>
                <td>Brand</td>
                <td><input type='text' size='30' name='brand' value='<?php echo $params['brand'] ?>' /></td>
            </tr>
            <tr>
                <td>Type</td>
                <td><input type='text' size='30' name='type' value='<?php echo $params['type'] ?>' /></td>
            </tr>
            <tr>
                <td>Port</td>
                <td><input type='text' size='10' name='port' value='<?php echo $params['port'] ?>' /></td>
            </tr>
            <tr>
                <td>User Account</td>
                <td><input type='text' size='10' name='userAccount' value='<?php echo $params['userAccount'] ?>' /></td>
            </tr>
            <tr>
                <td>Lokasi</td>
                <td><input type='text' size='30' name='lokasi' value='<?php echo $params['lokasi'] ?>' /></td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type='reset' value='Reset'>
    <input type='submit' value='Simpan' name='btx'>
</form>
