<h3>Report Komputer</h3>
<?php if (!empty($errorMessages)) : ?>
<ul>
    <?php foreach ($errorMessages as $errorMessage) : ?>
        <li><?php echo $errorMessage ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<form action='' method='post'>
    <table border='0' width='100%'>
        <tbody>
            <tr>
                <td>Mac Address</td>
                <td><input type='text' size='30' name='mac' value='<?php echo $params['mac'] ?>'></td>
            </tr>
            <tr>
                <td>Nomor Seri</td>
                <td><input type='text' size='30' name='nomorSeri' value='<?php echo $params['nomorSeri'] ?>'></td>
            </tr>
            <tr>
                <td>Sistem Operasi</td>
                <td>
                    <select name='sistemOperasi'>
                        <option value=''>[ semua ]</option>
                        <option value='Windows 7 Home Basic 32-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Home Basic 32-Bit' ? ' selected' : '' ?>>Windows 7 Home Basic 32-Bit</option>
                        <option value='Windows 7 Home Basic 62-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Home Basic 62-Bit' ? ' selected' : '' ?>>Windows 7 Home Basic 62-Bit</option>
                        <option value='Windows 7 Home Premium 32-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Home Premium 32-Bit' ? ' selected' : '' ?>>Windows 7 Home Premium 32-Bit</option>
                        <option value='Windows 7 Home Premium 64-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Home Premium 64-Bit' ? ' selected' : '' ?>>Windows 7 Home Premium 64-Bit</option>
                        <option value='Windows 7 Profesional 32-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Profesional 32-Bit' ? ' selected' : '' ?>>Windows 7 Profesional 32-Bit</option>
                        <option value='Windows 7 Profesional 64-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Profesional 64-Bit' ? ' selected' : '' ?>>Windows 7 Profesional 64-Bit</option>
                        <option value='Windows 7 Ultimate 32-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Ultimate 32-Bit' ? ' selected' : '' ?>>Windows 7 Ultimate 32-Bit</option>
                        <option value='Windows 7 Ultimate 64-Bit'<?php echo $params['sistemOperasi'] == 'Windows 7 Ultimate 64-Bit' ? ' selected' : '' ?>>Windows 7 Ultimate 64-Bit</option>
                        <option value='Windows Server 2012 64-bit'<?php echo $params['sistemOperasi'] == 'Windows Server 2012 64-bit' ? ' selected' : '' ?>>Windows Server 2012 64-bit</option>
                        <option value='Windows Server 2008 32-bit'<?php echo $params['sistemOperasi'] == 'Windows Server 2008 32-bit' ? ' selected' : '' ?>>Windows Server 2008 32-bit</option>
                        <option value='Windows Server 2008 64-bit'<?php echo $params['sistemOperasi'] == 'Windows Server 2008 64-bit' ? ' selected' : '' ?>>Windows Server 2008 64-bit</option>
                        <option value='Windows Storage Server 2012 64-bit'<?php echo $params['sistemOperasi'] == 'Windows Storage Server 2012 64-bit' ? ' selected' : '' ?>>Windows Storage Server 2012 64-bit</option>
                        <option value='Windows XP Professional 32-Bit'<?php echo $params['sistemOperasi'] == 'Windows XP Professional 32-Bit' ? ' selected' : '' ?>>Windows XP Professional 32-Bit</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Lokasi</td>
                <td>
                    <select name='lokasi'>
                        <option value=''>[ semua ]</option>
                        <option value='Dept. HRD/GA'<?php echo $params['lokasi'] == 'Dept. HRD/GA' ? ' selected' : '' ?>>Dept. HRD/GA</option>
                        <option value='Dept. Accounting'<?php echo $params['lokasi'] == 'Dept. Accounting' ? ' selected' : '' ?>>Dept. Accounting</option>
                        <option value='Dept. Marketing'<?php echo $params['lokasi'] == 'Dept. Marketing' ? ' selected' : '' ?>>Dept. Marketing</option>
                        <option value='Dept. Shipping'<?php echo $params['lokasi'] == 'Dept. Shipping' ? ' selected' : '' ?>>Dept. Shipping</option>
                        <option value='Dept. CMC'<?php echo $params['lokasi'] == 'Dept. CMC' ? ' selected' : '' ?>>Dept. CMC</option>
                        <option value='Dept. PPIC'<?php echo $params['lokasi'] == 'Dept. PPIC' ? ' selected' : '' ?>>Dept. PPIC</option>
                        <option value='Dept. Purchasing'<?php echo $params['lokasi'] == 'Dept. Purchasing' ? ' selected' : '' ?>>Dept. Purchasing</option>
                        <option value='Dept. Warehouse'<?php echo $params['lokasi'] == 'Dept. Warehouse' ? ' selected' : '' ?>>Dept. Warehouse</option>
                        <option value='Dept. IT'<?php echo $params['lokasi'] == 'Dept. IT' ? ' selected' : '' ?>>Dept. IT</option>
                        <option value='Dept. R&D'<?php echo $params['lokasi'] == 'Dept. R&D' ? ' selected' : '' ?>>Dept. R&D</option>
                        <option value='Dept. Finish Good'<?php echo $params['lokasi'] == 'Dept. Finish Good' ? ' selected' : '' ?>>Dept. Finish Good</option>
                        <option value='Dept. CNC'<?php echo $params['lokasi'] == 'Dept. CNC' ? ' selected' : '' ?>>Dept. CNC</option>
                        <option value='Dept. Maintenance'<?php echo $params['lokasi'] == 'Dept. Maintenance' ? ' selected' : '' ?>>Dept. Maintenance</option>
                        <option value='Dept. IQC'<?php echo $params['lokasi'] == 'Dept. IQC' ? ' selected' : '' ?>>Dept. IQC</option>
                        <option value='Dept. QC'<?php echo $params['lokasi'] == 'Dept. QC' ? ' selected' : '' ?>>Dept. QC</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>Tahun</td>
                <td><input type='text' size='30' name='tahun' value='<?php echo $params['tahun'] ?>'></td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type='reset' value='Reset'>
    <input type='submit' value='Proses' name='btx'>
</form>

<table>
    <thead>
        <tr>
            <th>No.</th>
            <th>Nomor Seri</th>
            <th>IP Address</th>
            <th>Mac Address</th>
            <th>Sistem Operasi</th>
            <th>User</th>
            <th>User Account</th>
            <th>Lokasi</th>
            <th>Tahun</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($data) > 0) :
            $number = 1;
            foreach ($data as $row) : ?>
        <tr>
            <td><?php echo $number++ ?></td>
            <td><?php echo $row->getNomorSeri() ?></td>
            <td><?php echo $row->getIp() ?></td>
            <td><?php echo $row->getMac() ?></td>
            <td><?php echo $row->getOs() ?></td>
            <td><?php echo $row->getUser() ?></td>
            <td><?php echo $row->getUserAccount() ?></td>
            <td><?php echo $row->getLokasi() ?></td>
            <td><?php echo $row->getTahun() ?></td>
            <td>
                <a href='<?php echo $this->routeManager->generateRoute(array('action' => 'view_komputer', 'key' => $row->getId())) ?>'>detail</a>
                <a href='<?php echo $this->routeManager->generateRoute(array('action' => 'edit_komputer', 'key' => $row->getId())) ?>'>revisi</a>
                <a href='<?php echo $this->routeManager->generateRoute(array('action' => 'delete_komputer', 'key' => $row->getId())) ?>'>hapus</a>
            </td>
        </tr>
        <?php endforeach;
            else : ?>
        <tr>
            <td colspan='0' style='text-align: center;'>Data kosong</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
