<h3>Master Cuti</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post" enctype="multipart/form-data">
    <fieldset>
        <div class="fieldset-kiri">NIK</div>
        <div class="fieldset-kanan"><?php echo $params['nik'] ?></div>
        <div class="fieldset-kiri">Nama Karyawan</div>
        <div class="fieldset-kanan"><?php echo $params['namaKaryawan'] ?></div>
        <div class="fieldset-kiri">Departemen</div>
        <div class="fieldset-kanan"><?php echo $params['departemen'] ?></div>
        <hr />
        <div><h3>Detail Cuti Periode Aktif</h3></div>
        <div class="fieldset-kiri">Sisa</div>
        <div class="fieldset-kanan"><?php echo $params['sisaCutiAktif'] ?></div>
        <div class="fieldset-kiri">Tanggal Kadaluarsa</div>
        <div class="fieldset-kanan"><?php echo $params['tanggalKadaluarsaAktif'] ?></div>
        <hr />
        <div><h3>Detail Cuti Periode Lalu (sisa cuti yang belum kadaluarsa)</h3></div>
        <div class="fieldset-kiri">Sisa</div>
        <div class="fieldset-kanan"><?php echo $params['sisaCutiPeriodeSebelumnya'] ?></div>
        <div class="fieldset-kiri">Tanggal Kadaluarsa</div>
        <div class="fieldset-kanan"><?php echo $params['tanggalKadaluarsaPeriodeSebelumnya'] ?></div>
        <hr />
        <div class="fieldset-kiri"></div>
        <div class="fieldset-button">
            <input type="submit" name="btx" value="Kembali" />
        </div>
    </fieldset>
</form>
