<h3>Master Cuti</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">'
            . 'Form yang anda kirim tidak valid.<br />Mohon dicek kembali.';

        if (!empty($errorMessages['global'])) {
            echo '<ul>';
            foreach ($errorMessages['global'] as $globalError) {
                echo '<li>' . $globalError . '</li>';
            }
            echo '</ul>';
        }

        echo '</div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>Departemen</td>
                <td>
                    <select name="departemen">
                        <option value="">[semua]</option>
                        <?php foreach ($departmentList as $department) : ?>
                        <option value="<?php echo $department ?>" <?php echo $params['departemen'] == $department ? 'selected="selected"' : '' ?>>
                            <?php echo $department ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>
<table class="content">
    <tr>
        <th rowspan=3>NIK</th>
        <th rowspan=3>Nama</th>
        <th rowspan=3>Departemen</th>
        <th rowspan=3>Hak Cuti</th>
        <th colspan=8>Detail Cuti</th>
        <th rowspan=3>Sisa Kumulatif</th>
        <th rowspan=3>Action</th>
    </tr>
    <tr>
        <th colspan=4>Aktif</th>
        <th colspan=4>Pasif</th>
    </tr>
    <tr>
        <th>Limit</th>
        <th>Diambil</th>
        <th>Pending</th>
        <th>Sisa</th>
        <th>Limit</th>
        <th>Diambil</th>
        <th>Pending</th>
        <th>Sisa</th>
    </tr>
    <?php
        if (! empty($data)) :
            foreach ($data as $report) :
    ?>
    <tr>
        <td><?php echo $report['fCode'] ?></td>
        <td class="nowrap"><?php echo $report['fName'] ?></td>
        <td class="nowrap"><?php echo $report['fDeptName'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fHakCuti'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fLimitAktif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fApprovedAktif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fPendingAktif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fSisaAktif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fLimitPasif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fApprovedPasif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fPendingPasif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fSisaPasif'] ?></td>
        <td class="nowrap" style="text-align:center;"><?php echo $report['fSisaKumulatif'] ?></td>
        <td class="nowrap" style="text-align:center;">
            <a href="<?php echo $this->routeManager->generateRoute(array(
                'action' => 'detail_master_cuti',
                'key' => $report['fCode']
            )) ?>">detail cuti</a>
        </td>
    </tr>
    <?php
            endforeach;
        else :
    ?>
    <tr>
        <td colspan=0 style="text-align:center;">Data tidak ditemukan!</td>
    </tr>
    <?php endif; ?>
</table>
<style type="text/css">
    .nowrap {
        white-space:nowrap;
    }
</style>
