<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
        <style type="text/css">
            body {
                width: 100%;
                text-align: center;
                font-size: 12px;
            }

            #print {
                width: 400px;
                margin: 0 auto 20px auto;
                border: 1px solid #000000;
            }

            .header {
                font-size: 15px;
            }

            .content {
                margin: 5px;
            }

            .title {
                margin-bottom: 5px;
                border: 1px solid #000000;
            }

            .body {
                padding: 2px;
                text-align: left;
                border: 1px solid #000000;
            }

            .fieldset-kiri {
                width: 100px;
                float: left;
                margin-bottom: 5px;
                clear: left;
                vertical-align: top;
            }

            .fieldset-kanan {
                margin-left: 100px;
                margin-bottom: 5px;
                vertical-align: top;
            }
            .fieldset-kanan:before {
                content: ': ';
                vertical-align: top;
            }

            .fieldset-both {
                margin-bottom: 5px;
            }

            .footer {
                margin; 5px;
            }

            .footer-date {
                margin: 5px;
                text-align: right;
            }

            .footer-sign div {
                width: 131px;
                float: left;
                margin-bottom: 5px;
            }

            @media print {
                input[type=submit],
                button {
                    display: none !important;
                }
            }
        </style>
    </head>
    <body>
        <form action="" method="post">
            <div id="container">
                <div id="print">
                    <div class="header">PT. Woodworth Wooden Industries Indonesia</div>
                    <div class="content">
                        <div class="title">
                            SURAT PERMOHONAN CUTI
                            <div class="sub-title">Form HRD xxx xxxx</div>
                        </div>
                        <div class="body">
                            <?php
                                //~$data = array(
                                    //~'tanggalPengajuan' => new \DateTime(),
                                    //~'nik' => '0000001',
                                    //~'namaKaryawan' => 'Nama Karyawan',
                                    //~'tanggalAwal' => new \DateTime(),
                                    //~'tanggalAkhir' => new \DateTime(),
                                    //~'keterangan' => 'Keterangan'
                                //~);
                            ?>
                            <?php if ($data !== null) : ?>
                            <div class="fieldset-kiri">Tanggal Pengajuan</div>
                            <div class="fieldset-kanan"><?php echo $data['tanggalPengajuan']->format('d/m/Y') ?></div>
                            <div class="fieldset-kiri">NIK</div>
                            <div class="fieldset-kanan"><?php echo $data['nik'] ?></div>
                            <div class="fieldset-kiri">Nama Karyawan</div>
                            <div class="fieldset-kanan"><?php echo $data['namaKaryawan'] ?></div>
                            <div class="fieldset-kiri">Tanggal Cuti</div>
                            <div class="fieldset-kanan">
                                <?php echo $data['tanggalAwal']->format('d/m/Y') ?> s/d
                                <?php echo $data['tanggalAkhir']->format('d/m/Y') ?>
                            </div>
                            <div class="fieldset-kiri">Keterangan</div>
                            <div class="fieldset-kanan"><?php echo nl2br($data['keterangan']) ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="footer">
                        <div class="footer-date">Tgl ....................</div>
                        <div class="footer-sign">
                            <div>
                                Mengetahui,<br />
                                HRD
                                <br /><br /><br />
                                ( .................... )
                            </div>
                            <div>
                                Disetujui oleh,<br />
                                Pimpinan Bagian
                                <br /><br /><br />
                                ( .................... )
                            </div>
                            <div>
                                Pemohon,<br />
                                <br /><br /><br />
                                ( .................... )
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>
            </div>
            <div id="control">
                <button onclick="javascript:window.print()">Print</button>
                <input type="submit" name="btx" value="Kembali" />
            </div>
        </form>
    </body>
</html>
