<h3>Data Pelamar</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<form action="" method="post" enctype="multipart/form-data">
    <div>
        Apakah anda yakin akan menghapus data ini?
    </div>
    <table class='detail' border='0' width='100%'>
        <tbody>
            <tr>
                <td>Nama Pelamar</td>
                <td><?php echo $params['namaLengkap'] ?></td>
            </tr>
            <tr>
                <td>Alamat</td>
                <td>
                    <?php echo $params['alamat'] ?><br />
                    <?php echo $params['kota'] ?>
                </td>
            </tr>
            <tr>
                <td>Pendidikan</td>
                <td><?php echo $params['pendidikan'] ?></td>
            </tr>
            <tr>
                <td>Jurusan</td>
                <td><?php echo $params['jurusan'] ?></td>
            </tr>
            <tr>
                <td>Posisi</td>
                <td><?php echo $params['posisi'] ?></td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type='submit' name='btx' value='Batal' />
    <input type='submit' name='btx' value='Hapus' />
</form>

<style type="text/css">
    .fieldset-kiri {
        width: 150px;
        float: left;
        margin-bottom: 5px;
        clear: left;
        vertical-align: top;
    }

    .fieldset-kanan {
        margin-left: 150px;
        margin-bottom: 5px;
        vertical-align: top;
    }

    .fieldset-kanan:before {
        content: ': ';
        vertical-align: top;
    }

    .fieldset-empty:before {
        content: ' ';
    }

    .fieldset-button {
        margin-left: 157px;
        margin-bottom: 5px;
    }

    .required:after {
        content: ' *';
        color: red;
    }

    .error-head {
        color: red;
        font-weight: bold;
    }

    .error-container {
        color: red;
        margin-left: 7px;
    }
</style>

<script type="text/javascript">
</script>
