<h3>Report General Inspection</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>Tanggal Inspeksi</td>
                <td>
                    <input type="text" required id="tanggal" class="medium" name="tanggal" value="<?php echo $params['tanggal'] ?>">
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggal']) ? $errorMessages['tanggal'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Group/Departemen</td>
                <td>
                    <select name="group">
                        <option value="">[pilih satu]</option>
                        <?php foreach ($departmentList as $department) : ?>
                        <option value="<?php echo $department ?>" <?php echo $params['group'] == $department ? 'selected="selected"' : '' ?>>
                            <?php echo $department ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['group']) ? $errorMessages['group'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Lokasi</td>
                <td>
                    <input type="text" required id="lokasi" class="medium" name="lokasi" value="<?php echo $params['lokasi'] ?>" />
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggalInspeksi']) ? $errorMessages['tanggalInspeksi'] : '' ?>
                    </td>
                </td>
            </tr>
            <tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>

<table class="content">
    <thead>
        <tr>
            <th rowspan=0>No.</th>
            <th rowspan=0>Waktu</th>
            <th rowspan=0>Kode Produk</th>
            <th rowspan=0>Nama Produk</th>
            <th rowspan=0>Jumlah Inspeksi</th>
            <th colspan=28>Konten Kondisi Buruk</th>
            <th colspan=3>Kondisi Produksi</th>
            <th rowspan=0>Status</th>
        </tr>
        <tr>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Kain Tergores</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Tidak Presisi</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Salah Posisi Lubang</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Salah Ukuran</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Tergores</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Kelebihan Lem</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Struktur Longgar</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Cover Terpotong</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Retak</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Sanding Buruk</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Paku Keluar</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Lem Degumming</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Gap</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Lainnya</div></th>
            <th class="rotate"><div>----------</div></th>
            <th class="rotate"><div>Jumlah Kekurangan</div></th>
            <th>Jumlah Kualitas Buruk</th>
        </tr>
    </thead>
    <tbody>
        <?php
            if (count($data) > 0) :
                $number = 1;

                foreach ($data as $dailyInspection) :
                    $numberRowSpan = 1;
                    foreach ($dailyInspection->getDailyInspectionTime() as $timeGroup) {
                        $numberRowSpan++;
                        foreach ($timeGroup->getDailyInspectionItem() as $item) {
                            $numberRowSpan++;
                        }
                    }
        ?>
        <tr>
            <td rowspan=<?php echo $numberRowSpan ?>><?php echo $number++; ?></td>
        </tr>
        <?php
            foreach ($dailyInspection->getDailyInspectionTime() as $timeGroup) :
                $timeGroupRowSpan = count($timeGroup->getDailyInspectionItem()) + 1;
        ?>
        <tr>
            <td rowspan=<?php echo $timeGroupRowSpan; ?>><?php echo $timeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
        </tr>
        <?php foreach ($timeGroup->getDailyInspectionItem() as $item) : ?>
        <tr>
            <td><?php echo $item->getKodeProduk() ?></td>
            <td><?php echo $item->getNamaProduk() ?></td>
            <td style="text-align:right;"><?php echo $item->getJumlahInspeksi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemKainTergores() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemTidakPresisi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemSalahPosisiLubang() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemSalahUkuran() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemTergores() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemKelebihanLem() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemStrukturLonggar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemCoverTerpotong() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemRetak() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemSandingBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemPakuKeluar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemLemDegumming() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemGap() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemBurukLainnya() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemKekurangan() ?></td>
            <td style="text-align:right;"><?php echo $item->getJumlahTotalItemBuruk() ?></td>
            <td style="text-align:center;"><?php echo $this->inspectionStatusHelper->getInspectionStatus($item) ? 'v' : 'x' ?></td>
        </tr>
        <?php
                        endforeach;
                    endforeach;
                endforeach;
            else :
        ?>
        <tr>
            <td colspan=0 style="text-align:center;">Data kosong!</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>

<style type="text/css">
    fieldset {
        border: 1px solid;
    }

    table.content thead tr:first-child {
        height: 30px;
    }

    table.content thead tr:last-child {
        height: 120px;
    }

    table.content thead tr th.rotate {
        padding: 0;
        white-space: nowrap;
    }

    table.content thead tr th.rotate > div {
        transform:
            translate(0, 40px)
            rotate(270deg);
        width: 30px;
    }

    table.content tbody td {
        vertical-align: top;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $("#tanggal").datepicker({
            dateFormat: 'dd/mm/yy',
            yearRange: '-55:-0'
        });
    });
</script>
