<h3>Report General Inspection - Packaging</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>日 期 Tanggal Inspeksi</td>
                <td>
                    <input type="text" required id="tanggal" class="medium" name="tanggal" value="<?php echo $params['tanggal'] ?>">
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggal']) ? $errorMessages['tanggal'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>定 位 點 Lokasi</td>
                <td>
                    <select id="lokasi" name="lokasi">
                        <option value="">[ 选 一 项 pilih satu ]</option>
                        <option value="Gudang 1"<?php echo $params['lokasi'] == 'Gudang 1' ? ' selected' : '' ?>>Gudang 1</option>
                        <option value="Gudang 2"<?php echo $params['lokasi'] == 'Gudang 2' ? ' selected' : '' ?>>Gudang 2</option>
                        <option value="Gudang 3"<?php echo $params['lokasi'] == 'Gudang 3' ? ' selected' : '' ?>>Gudang 3</option>
                        <option value="Gudang 4"<?php echo $params['lokasi'] == 'Gudang 4' ? ' selected' : '' ?>>Gudang 4</option>
                        <option value="Gudang 5"<?php echo $params['lokasi'] == 'Gudang 5' ? ' selected' : '' ?>>Gudang 5</option>
                        <option value="Gudang 6"<?php echo $params['lokasi'] == 'Gudang 6' ? ' selected' : '' ?>>Gudang 6</option>
                        <option value="Gudang 7"<?php echo $params['lokasi'] == 'Gudang 7' ? ' selected' : '' ?>>Gudang 7</option>
                        <option value="Gudang 8"<?php echo $params['lokasi'] == 'Gudang 8' ? ' selected' : '' ?>>Gudang 8</option>
                        <option value="Gudang 9"<?php echo $params['lokasi'] == 'Gudang 9' ? ' selected' : '' ?>>Gudang 9</option>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['lokasi']) ? $errorMessages['lokasi'] : '' ?>
                    </td>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>
<?php
    if ($data !== null) :
        $packagingInspectionTime = $data->getPackagingInspectionTime();
?>
<table class="content">
    <thead>
        <tr>
            <th rowspan=0 style="width: 40px;">時 間<br />Waktu</th>
            <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
            <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
            <th rowspan=0 style="width:40px;">批<br />数<br />量<br />Jumlah Lot</th>
            <th rowspan=0 style="width:40px;">檢<br />驗<br />數<br />Jumlah Inspeksi</th>
            <th colspan=36>不 良 內 容<br />Konten Kondisi Buruk</th>
            <th colspan=3>生 產 狀 況<br />Kondisi Produksi</th>
        </tr>
        <tr>
            <th><div>流<br />程<br />错<br />误</div></th>
            <th class="rotate"><div>Salah Flow Proses</div></th>
            <th><div>材<br />质<br />不<br />良</div></th>
            <th class="rotate"><div>Kualitas Buruk</div></th>
            <th><div>材<br />质<br />不<br />對</div></th>
            <th class="rotate"><div>Salah Kualitas</div></th>
            <th><div>孔<br />位<br />不<br />對</div></th>
            <th class="rotate"><div>Salah Posisi Lubang</div></th>
            <th><div>角<br />度<br />不<br />一<br />致</div></th>
            <th class="rotate"><div>Salah Ukuran</div></th>
            <th><div>跳<br />刀<br />痕</div></th>
            <th class="rotate"><div>Bekas Goresan Pisau</div></th>
            <th><div>撕<br />裂</div></th>
            <th class="rotate"><div>Sobek</div></th>
            <th><div>開<br />裂</div></th>
            <th class="rotate"><div>Retak</div></th>
            <th><div>发<br />黑</div></th>
            <th class="rotate"><div>Hitam</div></th>
            <th><div>砂<br />光<br />不<br />良</div></th>
            <th class="rotate"><div>Sanding Buruk</div></th>
            <th><div>压<br />划<br />伤</div></th>
            <th class="rotate"><div>Goresan Tekanan</div></th>
            <th><div>冒<br />钉</div></th>
            <th class="rotate"><div>Paku Keluar</div></th>
            <th><div>组<br />立<br />不<br />良</div></th>
            <th class="rotate"><div>Berdiri Buruk</div></th>
            <th><div>修<br />补<br />不<br />良</div></th>
            <th class="rotate"><div>Perbaikan Buruk</div></th>
            <th><div>脫<br />膠</div></th>
            <th class="rotate"><div>Lem Degumming</div></th>
            <th><div>溢<br />膠</div></th>
            <th class="rotate"><div>Kelebihan Lem</div></th>
            <th><div>湿<br />度<br />太<br />高</div></th>
            <th class="rotate"><div>Suhu Terlalu Tinggi</div></th>
            <th><div>其<br />他</div></th>
            <th class="rotate"><div>Lainnya</div></th>
            <th><div>缺<br />點<br />數</div></th>
            <th class="rotate"><div>Jumlah Kekurangan</div></th>
            <th>不<br />良<br />數<br /><strong>Jumlah Kualitas Buruk</strong></th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($packagingInspectionTime as $packagingTimeGroup) :
                $packagingTimeGroupRowSpan = count($packagingTimeGroup->getPackagingInspectionItem()) + 1;
        ?>
        <tr>
            <td rowspan=<?php echo $packagingTimeGroupRowSpan; ?>><?php echo $packagingTimeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
        </tr>
        <?php
            foreach ($packagingTimeGroup->getPackagingInspectionItem() as $packagingItem) :
        ?>
        <tr>
            <td><?php echo $packagingItem->getKodeProduk() ?></td>
            <td><?php echo $packagingItem->getNamaProduk() ?></td>
            <td style="text-align:right;"><?php echo $packagingItem->getJumlahLot() ?></td>
            <td style="text-align:right;"><?php echo $packagingItem->getJumlahInspeksi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSalahFlowProses() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemKualitasBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSalahKualitas() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSalahPosisiLubang() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSalahUkuran() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemBekasGoresanPisau() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSobek() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemRetak() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemHitam() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSandingBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemGoresanTekanan() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemPakuKeluar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemBerdiriBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemPerbaikanBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemLemDegumming() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemKelebihanLem() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemSuhuTerlaluTinggi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemBurukLainnya() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $packagingItem->getJumlahItemKekurangan() ?></td>
            <td style="text-align:right;"><?php echo $packagingItem->getJumlahTotalItemBuruk() ?></td>
        </tr>
    </tr>
        <?php
                endforeach;
            endforeach;
        ?>
    </tbody>
</table>
<input
    type="button"
    value="Print"
    onclick="javascript:window.location.href='<?php
        echo $this->routeManager->generateRoute(array(
            'action' => 'report_general_inspection_packaging_print',
            'key' => $data->getId(),
            'print' => true
        ));
    ?>'">
<?php else: ?>
<div style="text-align:center;"><h3>Data tidak ditemukan!</h3></div>
<?php endif; ?>
<style type="text/css">
    fieldset {
        border: 1px solid;
    }

    table.content thead tr:first-child {
        height: 30px;
    }

    table.content thead tr:last-child {
        height: 120px;
    }

    table.content thead tr th.rotate {
        padding: 0;
        white-space: nowrap;
    }

    table.content thead tr th.rotate > div {
        transform:
            translate(0, 40px)
            rotate(270deg);
        width: 30px;
    }

    table.content tbody td {
        vertical-align: top;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $("#tanggal").datepicker({
            dateFormat: 'dd/mm/yy',
            yearRange: '-55:-0'
        });
    });
</script>
