<h3>Report General Inspection - Whitewood</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>日期 Tanggal Inspeksi</td>
                <td>
                    <input type="text" required id="tanggal" class="medium" name="tanggal" value="<?php echo $params['tanggal'] ?>">
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggal']) ? $errorMessages['tanggal'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>定位點 Lokasi</td>
                <td>
                    <select id="lokasi" name="lokasi">
                        <option value="">[ 选一项 pilih satu ]</option>
                        <option value="Line 1"<?php echo $params['lokasi'] == 'Line 1' ? ' selected' : '' ?>>Line 1</option>
                        <option value="Line 2"<?php echo $params['lokasi'] == 'Line 2' ? ' selected' : '' ?>>Line 2</option>
                        <option value="Line 3"<?php echo $params['lokasi'] == 'Line 3' ? ' selected' : '' ?>>Line 3</option>
                        <option value="Line 4"<?php echo $params['lokasi'] == 'Line 4' ? ' selected' : '' ?>>Line 4</option>
                        <option value="Line 5"<?php echo $params['lokasi'] == 'Line 5' ? ' selected' : '' ?>>Line 5</option>
                        <option value="Line 6"<?php echo $params['lokasi'] == 'Line 6' ? ' selected' : '' ?>>Line 6</option>
                        <option value="Line 7"<?php echo $params['lokasi'] == 'Line 7' ? ' selected' : '' ?>>Line 7</option>
                        <option value="Line 8"<?php echo $params['lokasi'] == 'Line 8' ? ' selected' : '' ?>>Line 8</option>
                        <option value="Line 9"<?php echo $params['lokasi'] == 'Line 9' ? ' selected' : '' ?>>Line 9</option>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['lokasi']) ? $errorMessages['lokasi'] : '' ?>
                    </td>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>
<?php
    if ($data !== null) :
        $whitewoodInspectionTime = $data->getWhitewoodInspectionTime();
?>
<table class="content">
    <thead>
        <tr>
            <th rowspan=0 style="width: 40px;">時 間<br />Waktu</th>
            <th rowspan=0 style="width:40px;">客<br />戶<br />Customer</th>
            <th rowspan=0 style="width:40px;">PO</th>
            <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
            <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
            <th rowspan=0 style="width:40px;">批<br />数<br />量<br />Jumlah Lot</th>
            <th rowspan=0 style="width:40px;">檢<br />驗<br />數<br />Jumlah Inspeksi</th>
            <th colspan=38>不 良 內 容<br />Konten Kondisi Buruk</th>
            <th colspan=0>生 產 狀 況<br />Kondisi Produksi</th>
            <th rowspan=0 style="width:40px;">狀<br />態<br />Status</th>
        </tr>
        <tr>
            <th><div>[X]<br />[X]<br />[X]<br />[X]</div></th>
            <th class="rotate"><div>Salah Proses</div></th>
            <th><div>材<br />质<br />不<br />良</div></th>
            <th class="rotate"><div>Kualitas Buruk</div></th>
            <th><div>材<br />质<br />不<br />對</div></th>
            <th class="rotate"><div>Kualitas Tidak Benar</div></th>
            <th><div>孔<br />位<br />不<br />對</div></th>
            <th class="rotate"><div>Posisi Lubang Salah</div></th>
            <th><div>尺<br />寸<br />不<br />對</div></th>
            <th class="rotate"><div>Salah Ukuran</div></th>
            <th><div>[X]<br />[X]<br />[X]<br />[X]</div></th>
            <th class="rotate"><div>Salah Jenis Pisau</div></th>
            <th><div>跳<br />刀<br />痕</div></th>
            <th class="rotate"><div>Goresan Pisau</div></th>
            <th><div>撕<br />裂</div></th>
            <th class="rotate"><div>Robek</div></th>
            <th><div>開<br />裂</div></th>
            <th class="rotate"><div>Retak</div></th>
            <th><div>发<br />黑</div></th>
            <th class="rotate"><div>Menjadi Hitam</div></th>
            <th><div>砂<br />光<br />不<br />良</div></th>
            <th class="rotate"><div>Sanding Buruk</div></th>
            <th><div>压<br />划<br />伤</div></th>
            <th class="rotate"><div>Goresan Tekanan</div></th>
            <th><div>冒<br />钉</div></th>
            <th class="rotate"><div>Paku Keluar</div></th>
            <th><div>組<br />立<br />不<br />良</div></th>
            <th class="rotate"><div>Assembly Buruk</div></th>
            <th><div>修<br />补<br />不<br />良</div></th>
            <th class="rotate"><div>Perbaikan Buruk</div></th>
            <th><div>脫<br />膠</div></th>
            <th class="rotate"><div>Degumming</div></th>
            <th><div>溢<br />膠</div></th>
            <th class="rotate"><div>Kelebihan Lem</div></th>
            <th><div>湿<br />度<br />太<br />高</div></th>
            <th class="rotate"><div>Suhu Terlalu Tinggi</div></th>
            <th><div>其<br />他</div></th>
            <th class="rotate"><div>Lainnya</div></th>
            <th>不<br />良<br />數<br /><strong>Jumlah Kualitas Buruk</strong></th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($whitewoodInspectionTime as $whitewoodTimeGroup) :
                $whitewoodTimeGroupRowSpan = count($whitewoodTimeGroup->getWhitewoodInspectionItem()) + 1;
        ?>
        <tr>
            <td rowspan=<?php echo $whitewoodTimeGroupRowSpan; ?>><?php echo $whitewoodTimeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
        </tr>
        <?php
            foreach ($whitewoodTimeGroup->getWhitewoodInspectionItem() as $whitewoodItem) :
                $status = $this->inspectionStatusHelper->getInspectionStatus($whitewoodItem);
        ?>
        <tr>
            <td><?php echo $whitewoodItem->getCustomer() ?></td>
            <td><?php echo $whitewoodItem->getPO() ?></td>
            <td><?php echo $whitewoodItem->getKodeProduk() ?></td>
            <td><?php echo $whitewoodItem->getNamaProduk() ?></td>
            <td style="text-align:right;"><?php echo $whitewoodItem->getJumlahLot() ?></td>
            <td style="text-align:right;"><?php echo $whitewoodItem->getJumlahInspeksi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSalahProses() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemKualitasBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemKualitasTidakBenar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemPosisiLubangSalah() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSalahUkuran() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSalahJenisPisau() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemGoresanPisau() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemRobek() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemRetak() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemMenjadiHitam() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSandingBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemGoresanTekanan() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemPakuKeluar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemAssemblyBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemPerbaikanBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemDegumming() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemKelebihanLem() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSuhuTerlaluTinggi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemBurukLainnya() ?></td>
            <td style="text-align:right;"><?php echo $whitewoodItem->getJumlahTotalItemBuruk() ?></td>
            <td style="text-align:center; color:<?php echo $status ? 'green' : 'red' ?>"><?php echo $status ? 'pass' : 'fail' ?></td>
        </tr>
        <?php
                endforeach;
            endforeach;
         ?>
    </tbody>
</table>
<input
    type="button"
    value="Print"
    onclick="javascript:window.location.href='<?php
        echo $this->routeManager->generateRoute(array(
            'action' => 'report_general_inspection_whitewood_print',
            'key' => $data->getId(),
            'print' => true
        ));
    ?>'">
<?php else: ?>
<div style="text-align:center;"><h3>Data tidak ditemukan!</h3></div>
<?php endif; ?>
<style type="text/css">
    fieldset {
        border: 1px solid;
    }

    table.content thead tr:first-child {
        height: 30px;
    }

    table.content thead tr:last-child {
        height: 120px;
    }

    table.content thead tr th.rotate {
        padding: 0;
        white-space: nowrap;
    }

    table.content thead tr th.rotate > div {
        transform:
            translate(0, 40px)
            rotate(270deg);
        width: 30px;
    }

    table.content tbody td {
        vertical-align: top;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $("#tanggal").datepicker({
            dateFormat: 'dd/mm/yy',
            yearRange: '-55:-0'
        });
    });
</script>
