<h3>Report General Inspection - Assembling</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>日 期 Tanggal Inspeksi</td>
                <td>
                    <input type="text" required id="tanggal" class="medium" name="tanggal" value="<?php echo $params['tanggal'] ?>">
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggal']) ? $errorMessages['tanggal'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>定 位 點 Lokasi</td>
                <td>
                    <select id="lokasi" name="lokasi">
                        <option value="">[ 选 一 项 pilih satu ]</option>
                        <option value="Gudang 1"<?php echo $params['lokasi'] == 'Gudang 1' ? ' selected' : '' ?>>Gudang 1</option>
                        <option value="Gudang 2"<?php echo $params['lokasi'] == 'Gudang 2' ? ' selected' : '' ?>>Gudang 2</option>
                        <option value="Gudang 3"<?php echo $params['lokasi'] == 'Gudang 3' ? ' selected' : '' ?>>Gudang 3</option>
                        <option value="Gudang 4"<?php echo $params['lokasi'] == 'Gudang 4' ? ' selected' : '' ?>>Gudang 4</option>
                        <option value="Gudang 5"<?php echo $params['lokasi'] == 'Gudang 5' ? ' selected' : '' ?>>Gudang 5</option>
                        <option value="Gudang 6"<?php echo $params['lokasi'] == 'Gudang 6' ? ' selected' : '' ?>>Gudang 6</option>
                        <option value="Gudang 7"<?php echo $params['lokasi'] == 'Gudang 7' ? ' selected' : '' ?>>Gudang 7</option>
                        <option value="Gudang 8"<?php echo $params['lokasi'] == 'Gudang 8' ? ' selected' : '' ?>>Gudang 8</option>
                        <option value="Gudang 9"<?php echo $params['lokasi'] == 'Gudang 9' ? ' selected' : '' ?>>Gudang 9</option>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['lokasi']) ? $errorMessages['lokasi'] : '' ?>
                    </td>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>
<?php
    if ($data !== null) :
        $assemblingInspectionTime = $data->getAssemblingInspectionTime();
?>
<table class="content">
    <thead>
        <tr>
            <th rowspan=0 style="width: 40px;">時 間<br />Waktu</th>
            <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
            <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
            <th rowspan=0 style="width:40px;">批<br />数<br />量<br />Jumlah Lot</th>
            <th rowspan=0 style="width:40px;">檢<br />驗<br />數<br />Jumlah Inspeksi</th>
            <th colspan=28>不 良 內 容<br />Konten Kondisi Buruk</th>
            <th colspan=3>生 產 狀 況<br />Kondisi Produksi</th>
        </tr>
        <tr>
            <th><div>絨<br />布<br />劃<br />傷</div></th>
            <th class="rotate"><div>Kain Tergores</div></th>
            <th><div>抽<br />斗<br />配<br />套</div></th>
            <th class="rotate"><div>Tidak Presisi</div></th>
            <th><div>孔<br />位<br />不<br />對</div></th>
            <th class="rotate"><div>Salah Posisi Lubang</div></th>
            <th><div>尺<br />寸<br />不<br /> 對</div></th>
            <th class="rotate"><div>Salah Ukuran</div></th>
            <th><div>劃<br />傷</div></th>
            <th class="rotate"><div>Tergores</div></th>
            <th><div>溢<br />膠</div></div></th>
            <th class="rotate"><div>Kelebihan Lem</div></th>
            <th><div>結<br />構<br />鬆<br />動</div></th>
            <th class="rotate"><div>Struktur Longgar</div></th>
            <th><div>崩<br />缺</div></th>
            <th class="rotate"><div>Cover Terpotong</div></th>
            <th><div>開<br />裂</div></th>
            <th class="rotate"><div>Retak</div></th>
            <th><div>砂<br />光<br />不<br />良</div></th>
            <th class="rotate"><div>Sanding Buruk</div></th>
            <th><div>冒<br />钉</div></th>
            <th class="rotate"><div>Paku Keluar</div></th>
            <th><div>脫<br />膠</div></th>
            <th class="rotate"><div>Lem Degumming</div></th>
            <th><div>縫<br />隙</div></th>
            <th class="rotate"><div>Gap</div></th>
            <th><div>其<br />他</div></th>
            <th class="rotate"><div>Lainnya</div></th>
            <th><div>缺<br />點<br />數</div></th>
            <th class="rotate"><div>Jumlah Kekurangan</div></th>
            <th>不<br />良<br />數<br />Jumlah Kualitas Buruk</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($assemblingInspectionTime as $assemblingTimeGroup) :
                $assemblingTimeGroupRowSpan = count($assemblingTimeGroup->getAssemblingInspectionItem()) + 1;
        ?>
        <tr>
            <td rowspan=<?php echo $assemblingTimeGroupRowSpan; ?>><?php echo $assemblingTimeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
        </tr>
        <?php foreach ($assemblingTimeGroup->getAssemblingInspectionItem() as $assemblingItem) : ?>
        <tr>
            <td><?php echo $assemblingItem->getKodeProduk() ?></td>
            <td><?php echo $assemblingItem->getNamaProduk() ?></td>
            <td style="text-align:right;"><?php echo $assemblingItem->getJumlahLot() ?></td>
            <td style="text-align:right;"><?php echo $assemblingItem->getJumlahInspeksi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemKainTergores() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemTidakPresisi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemSalahPosisiLubang() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemSalahUkuran() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemTergores() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemKelebihanLem() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemStrukturLonggar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemCoverTerpotong() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemRetak() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemSandingBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemPakuKeluar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemLemDegumming() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemGap() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemBurukLainnya() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $assemblingItem->getJumlahItemKekurangan() ?></td>
            <td style="text-align:right;"><?php echo $assemblingItem->getJumlahTotalItemBuruk() ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
    <?php endforeach; ?>
</table>
<input
    type="button"
    value="Print"
    onclick="javascript:window.location.href='<?php
        echo $this->routeManager->generateRoute(array(
            'action' => 'report_general_inspection_assembling_print',
            'key' => $data->getId(),
            'print' => true
        ));
    ?>'">
<?php else: ?>
<div style="text-align:center;"><h3>Data tidak ditemukan!</h3></div>
<?php endif; ?>
<style type="text/css">
    fieldset {
        border: 1px solid;
    }

    table.content thead tr:first-child {
        height: 30px;
    }

    table.content thead tr:last-child {
        height: 120px;
    }

    table.content thead tr th.rotate {
        padding: 0;
        white-space: nowrap;
    }

    table.content thead tr th.rotate > div {
        transform:
            translate(0, 40px)
            rotate(270deg);
        width: 30px;
    }

    table.content tbody td {
        vertical-align: top;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $("#tanggal").datepicker({
            dateFormat: 'dd/mm/yy',
            yearRange: '-55:-0'
        });
    });
</script>
