<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
        <style type="text/css">
            @media print {
                button {
                    display: none !important;
                }
            }

            body {
                width: 26cm;
                text-align: center;
                font-family: "segoe ui";
                font-size: 10px;
                margin: 0 auto;
            }

            #footer {
                margin-top: 20px;
            }

            #content-head {
                margin-bottom: 5px;
            }

            #content-head span {
                margin-right: 40px;
            }

            #content-head span:last-child {
                margin-right: 0px;
            }

            table.full-border {
                width: 100%;
                margin: 0 auto;
                border-collapse: collapse;
                border: 1px solid #000000;
            }

            table.full-border th,
            table.full-border td {
                font-weight: normal;
                border: 1px solid #000000;
            }

            table.full-border td {
                text-align: left;
            }

            fieldset {
                border: 1px solid;
            }

            table.full-border thead tr:first-child {
                height: 30px;
            }

            table.full-border thead tr:last-child {
                height: 100px;
            }

            table.full-border thead tr th.rotate {
                padding: 0;
                white-space: nowrap;
            }

            table.full-border thead tr th.rotate > div {
                transform:
                    translate(0, 37px)
                    rotate(270deg);
                width: 17px;
            }

            table.full-border tbody td {
                vertical-align: top;
            }
        </style>
    </head>
    <body>
        <div id="head">
            <h3>
                [X] [X] [X] [X] [X] [X] [X] [X] [X] [X] [X]
                <br />
                Laporan Harian Proses Sampling Dan Testing Whitewood
            </h3>
        </div>
        <div id="content" style="overflow:auto;">
            <?php if ($data !== null) : ?>
            <div id="content-head">
                <div style="float:left;">
                    <span>組 別 Group : Whitewood</span>
                    <span>定 位 點 Lokasi : <?php echo $data->getLokasi(); ?></span>
                    <span>品 管 員 Staff  QC : <?php echo $data->getStaffQc(); ?></span>
                </div>
                <div style="float:right;">
                    <span><?php echo $data->getTanggalInspeksi()->format('Y'); ?> 年Thn</span>
                    <span><?php echo $data->getTanggalInspeksi()->format('m'); ?> 月Bln</span>
                    <span><?php echo $data->getTanggalInspeksi()->format('d'); ?> 日Tgl</span>
                </div>
            </div>
            <table class="full-border">
                <?php
                    $whitewoodInspectionTime = $data->getWhitewoodInspectionTime();
                ?>
                <thead>
                    <tr>
                        <th rowspan=0 style="width: 40px;">時 間<br />Waktu</th>
                        <th rowspan=0 style="width:40px;">客<br />戶<br />Customer</th>
                        <th rowspan=0 style="width:40px;">PO</th>
                        <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
                        <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
                        <th rowspan=0 style="width:40px;">批<br />数<br />量<br />Jumlah Lot</th>
                        <th rowspan=0 style="width:40px;">檢<br />驗<br />數<br />Jumlah Inspeksi</th>
                        <th colspan=38>不 良 內 容<br />Konten Kondisi Buruk</th>
                        <th colspan=0>生 產 狀 況<br />Kondisi Produksi</th>
                        <th rowspan=0 style="width:40px;">狀<br />態<br />Status</th>
                    </tr>
                    <tr>
                        <th><div>[X]<br />[X]<br />[X]<br />[X]</div></th>
                        <th class="rotate"><div>Salah Proses</div></th>
                        <th><div>材<br />质<br />不<br />良</div></th>
                        <th class="rotate"><div>Kualitas Buruk</div></th>
                        <th><div>材<br />质<br />不<br />對</div></th>
                        <th class="rotate"><div>Kualitas Tidak Benar</div></th>
                        <th><div>孔<br />位<br />不<br />對</div></th>
                        <th class="rotate"><div>Posisi Lubang Salah</div></th>
                        <th><div>尺<br />寸<br />不<br />對</div></th>
                        <th class="rotate"><div>Salah Ukuran</div></th>
                        <th><div>[X]<br />[X]<br />[X]<br />[X]</div></th>
                        <th class="rotate"><div>Salah Jenis Pisau</div></th>
                        <th><div>跳<br />刀<br />痕</div></th>
                        <th class="rotate"><div>Goresan Pisau</div></th>
                        <th><div>撕<br />裂</div></th>
                        <th class="rotate"><div>Robek</div></th>
                        <th><div>開<br />裂</div></th>
                        <th class="rotate"><div>Retak</div></th>
                        <th><div>发<br />黑</div></th>
                        <th class="rotate"><div>Menjadi Hitam</div></th>
                        <th><div>砂<br />光<br />不<br />良</div></th>
                        <th class="rotate"><div>Sanding Buruk</div></th>
                        <th><div>压<br />划<br />伤</div></th>
                        <th class="rotate"><div>Goresan Tekanan</div></th>
                        <th><div>冒<br />钉</div></th>
                        <th class="rotate"><div>Paku Keluar</div></th>
                        <th><div>組<br />立<br />不<br />良</div></th>
                        <th class="rotate"><div>Assembly Buruk</div></th>
                        <th><div>修<br />补<br />不<br />良</div></th>
                        <th class="rotate"><div>Perbaikan Buruk</div></th>
                        <th><div>脫<br />膠</div></th>
                        <th class="rotate"><div>Degumming</div></th>
                        <th><div>溢<br />膠</div></th>
                        <th class="rotate"><div>Kelebihan Lem</div></th>
                        <th><div>湿<br />度<br />太<br />高</div></th>
                        <th class="rotate"><div>Suhu Terlalu Tinggi</div></th>
                        <th><div>其<br />他</div></th>
                        <th class="rotate"><div>Lainnya</div></th>
                        <th>不<br />良<br />數<br /><strong>Jumlah Kualitas Buruk</strong></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        foreach ($whitewoodInspectionTime as $whitewoodTimeGroup) :
                            $whitewoodTimeGroupRowSpan = count($whitewoodTimeGroup->getWhitewoodInspectionItem()) + 1;
                    ?>
                    <tr>
                        <td rowspan=<?php echo $whitewoodTimeGroupRowSpan; ?>><?php echo $whitewoodTimeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
                    </tr>
                    <?php
                        foreach ($whitewoodTimeGroup->getWhitewoodInspectionItem() as $whitewoodItem) :
                            $status = $this->inspectionStatusHelper->getInspectionStatus($whitewoodItem);
                    ?>
                    <tr>
                        <td><?php echo $whitewoodItem->getCustomer() ?></td>
                        <td><?php echo $whitewoodItem->getPO() ?></td>
                        <td><?php echo $whitewoodItem->getKodeProduk() ?></td>
                        <td><?php echo $whitewoodItem->getNamaProduk() ?></td>
                        <td style="text-align:right;"><?php echo $whitewoodItem->getJumlahLot() ?></td>
                        <td style="text-align:right;"><?php echo $whitewoodItem->getJumlahInspeksi() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSalahProses() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemKualitasBuruk() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemKualitasTidakBenar() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemPosisiLubangSalah() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSalahUkuran() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSalahJenisPisau() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemGoresanPisau() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemRobek() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemRetak() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemMenjadiHitam() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSandingBuruk() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemGoresanTekanan() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemPakuKeluar() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemAssemblyBuruk() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemPerbaikanBuruk() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemDegumming() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemKelebihanLem() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemSuhuTerlaluTinggi() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $whitewoodItem->getJumlahItemBurukLainnya() ?></td>
                        <td style="text-align:right;"><?php echo $whitewoodItem->getJumlahTotalItemBuruk() ?></td>
                        <td style="text-align:center; color:<?php echo $status ? 'green' : 'red' ?>"><?php echo $status ? 'pass' : 'fail' ?></td>
                    </tr>
                    <?php
                            endforeach;
                        endforeach;
                     ?>
                </tbody>
            </table>
            <?php else: ?>
            <div style="text-align:center;"><h3>Data tidak ditemukan!</h3></div>
            <?php endif; ?>
        </div>
        <div id="footer">
            <button onclick="javascript: window.print()">Print</button>
            <button onclick="javascript: window.location.href = '<?php echo $this->routeManager->generateRoute(array('action' => 'report_general_inspection_whitewood')) ?>'">Kembali</button>
        </div>
    </body>
</html>
