<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
        <style type="text/css">
            @media print {
                button {
                    display: none !important;
                }
            }

            body {
                width: 26cm;
                text-align: center;
                font-family: "segoe ui";
                font-size: 10px;
                margin: 0 auto;
            }

            #footer {
                margin-top: 20px;
            }

            #content-head {
                margin-bottom: 5px;
            }

            #content-head span {
                margin-right: 40px;
            }

            #content-head span:last-child {
                margin-right: 0px;
            }

            table.full-border {
                width: 100%;
                margin: 0 auto;
                border-collapse: collapse;
                border: 1px solid #000000;
            }

            table.full-border th,
            table.full-border td {
                font-weight: normal;
                border: 1px solid #000000;
            }

            table.full-border td {
                text-align: left;
            }

            fieldset {
                border: 1px solid;
            }

            table.full-border thead tr:first-child {
                height: 30px;
            }

            table.full-border thead tr:last-child {
                height: 100px;
            }

            table.full-border thead tr th.rotate {
                padding: 0;
                white-space: nowrap;
            }

            table.full-border thead tr th.rotate > div {
                transform:
                    translate(0, 30px)
                    rotate(270deg);
                width: 20px;
            }

            table.full-border tbody td {
                vertical-align: top;
            }
        </style>
    </head>
    <body>
        <div id="head">
            <h3>
                品 管 全 檢 製 程 日 報 表
                <br />
                Laporan Harian Inspeksi Seluruh Proses QC
            </h3>
        </div>
        <div id="content" style="overflow:auto;">
            <?php if ($data !== null) : ?>
            <div id="content-head">
                <div style="float:left;">
                    <span>組 別 Group : Finishing</span>
                    <span>定 位 點 Lokasi : <?php echo $data->getLokasi(); ?></span>
                    <span>品 管 員 Staff  QC : <?php echo $data->getStaffQc(); ?></span>
                </div>
                <div style="float:right;">
                    <span><?php echo $data->getTanggalInspeksi()->format('Y'); ?> 年Thn</span>
                    <span><?php echo $data->getTanggalInspeksi()->format('m'); ?> 月Bln</span>
                    <span><?php echo $data->getTanggalInspeksi()->format('d'); ?> 日Tgl</span>
                </div>
            </div>
            <table class="full-border">
                <?php
                    $finishingInspectionTime = $data->getFinishingInspectionTime();
                ?>
                <thead>
                    <tr>
                        <th rowspan=0 style="width: 40px;">時 間<br />Waktu</th>
                        <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
                        <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
                        <th rowspan=0 style="width:40px;">批<br />数<br />量<br />Jumlah Lot</th>
                        <th rowspan=0 style="width:40px;">檢<br />驗<br />數<br />Jumlah Inspeksi</th>
                        <th colspan=30>不 良 內 容<br />Konten Kondisi Buruk</th>
                        <th colspan=3>生 產 狀 況<br />Kondisi Produksi</th>
                        <th rowspan=0 style="width:40px;">狀<br />態<br />Status</th>
                    </tr>
                    <tr>
                        <th><div>劃<br />傷</div></th>
                        <th class="rotate"><div>Tergores</div></th>
                        <th><div>抽<br />內<br />污<br />染</div></th>
                        <th class="rotate"><div>Terpolusi</div></th>
                        <th><div>尺<br />寸<br />不<br />對</div></th>
                        <th class="rotate"><div>Salah Ukuran</div></th>
                        <th><div>溢<br />膠</div></th>
                        <th class="rotate"><div>Kelebihan Lem</div></th>
                        <th><div>流<br />油</div></th>
                        <th class="rotate"><div>Kelebihan Cat</div></th>
                        <th><div>顏<br />色</div></th>
                        <th class="rotate"><div>Warna</div></th>
                        <th><div>氣<br />泡</div></th>
                        <th class="rotate"><div>Bergelembung</div></th>
                        <th><div>結<br />構<br />鬆<br />動</div></th>
                        <th class="rotate"><div>Struktur Longgar</div></th>
                        <th><div>崩<br />缺</div></th>
                        <th class="rotate"><div>Cover Terpotong</div></th>
                        <th><div>橫<br />砂<br />印</div></th>
                        <th class="rotate"><div>Arah Horizontal</div></th>
                        <th><div>砂<br />光<br />不<br />良</div></th>
                        <th class="rotate"><div>Sanding Buruk</div></th>
                        <th><div>冒<br />钉</div></th>
                        <th class="rotate"><div>Paku Keluar</div></th>
                        <th><div>脫<br />膠</div></th>
                        <th class="rotate"><div>Lem Degumming</div></th>
                        <th><div>縫<br />隙</div></th>
                        <th class="rotate"><div>Gap</div></th>
                        <th><div>其<br />他</div></th>
                        <th class="rotate"><div>Lainnya</div></th>
                        <th><div>缺<br />點<br />數</div></th>
                        <th class="rotate"><div>Jumlah Kekurangan</div></th>
                        <th style="width: 40px;">不<br />良<br />數<br />Jumlah Kualitas Buruk</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                        foreach ($finishingInspectionTime as $finishingTimeGroup) :
                            $finishingTimeGroupRowSpan = count($finishingTimeGroup->getFinishingInspectionItem()) + 1;
                    ?>
                    <tr>
                        <td rowspan=<?php echo $finishingTimeGroupRowSpan; ?>><?php echo $finishingTimeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
                    </tr>
                    <?php
                        foreach ($finishingTimeGroup->getFinishingInspectionItem() as $finishingItem) :
                            $status = $this->inspectionStatusHelper->getInspectionStatus($finishingItem);
                    ?>
                    <tr>
                        <td><?php echo $finishingItem->getKodeProduk() ?></td>
                        <td><?php echo $finishingItem->getNamaProduk() ?></td>
                        <td style="text-align:right;"><?php echo $finishingItem->getJumlahLot() ?></td>
                        <td style="text-align:right;"><?php echo $finishingItem->getJumlahInspeksi() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemTergores() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemTerpolusi() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemSalahUkuran() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemKelebihanLem() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemKelebihanCat() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemWarna() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemBergelembung() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemStrukturLonggar() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemCoverTerpotong() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemArahHorizontal() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemSandingBuruk() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemPakuKeluar() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemLemDegumming() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemGap() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemBurukLainnya() ?></td>
                        <td colspan=2 style="text-align:right;"><?php echo $finishingItem->getJumlahItemKekurangan() ?></td>
                        <td style="text-align:right;"><?php echo $finishingItem->getJumlahTotalItemBuruk() ?></td>
                        <td style="text-align:center; color:<?php echo $status ? 'green' : 'red' ?>"><?php echo $status ? 'pass' : 'fail' ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                <?php endforeach; ?>
            </table>
            <?php else: ?>
            <div style="text-align:center;"><h3>Data tidak ditemukan!</h3></div>
            <?php endif; ?>
        </div>
        <div id="footer">
            <button onclick="javascript: window.print()">Print</button>
            <button onclick="javascript: window.location.href = '<?php echo $this->routeManager->generateRoute(array('action' => 'report_general_inspection_finishing')) ?>'">Kembali</button>
        </div>
    </body>
</html>
