<h3>Report General Inspection</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>日期 Tanggal Inspeksi</td>
                <td>
                    <input type="text" required id="tanggal" class="medium" name="tanggal" value="<?php echo $params['tanggal'] ?>">
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggal']) ? $errorMessages['tanggal'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>组/部门 Group/Departemen</td>
                <td>
                    <select name="group">
                        <option value="">[ 选一项 pilih satu ]</option>
                        <?php foreach ($departmentList as $department) : ?>
                        <option value="<?php echo $department ?>"<?php echo $params['group'] == $department ? ' selected="selected"' : '' ?>>
                            <?php echo $department ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['group']) ? $errorMessages['group'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>定位點 Lokasi</td>
                <td>
                    <select id="lokasi" name="lokasi">
                        <option value="">[ 选一项 pilih satu ]</option>
                        <option value="Gudang 1"<?php echo $params['lokasi'] == 'Gudang 1' ? ' selected' : '' ?>>Gudang 1</option>
                        <option value="Gudang 2"<?php echo $params['lokasi'] == 'Gudang 2' ? ' selected' : '' ?>>Gudang 2</option>
                        <option value="Gudang 3"<?php echo $params['lokasi'] == 'Gudang 3' ? ' selected' : '' ?>>Gudang 3</option>
                        <option value="Gudang 4"<?php echo $params['lokasi'] == 'Gudang 4' ? ' selected' : '' ?>>Gudang 4</option>
                        <option value="Gudang 5"<?php echo $params['lokasi'] == 'Gudang 5' ? ' selected' : '' ?>>Gudang 5</option>
                        <option value="Gudang 6"<?php echo $params['lokasi'] == 'Gudang 6' ? ' selected' : '' ?>>Gudang 6</option>
                        <option value="Gudang 7"<?php echo $params['lokasi'] == 'Gudang 7' ? ' selected' : '' ?>>Gudang 7</option>
                        <option value="Gudang 8"<?php echo $params['lokasi'] == 'Gudang 8' ? ' selected' : '' ?>>Gudang 8</option>
                        <option value="Gudang 9"<?php echo $params['lokasi'] == 'Gudang 9' ? ' selected' : '' ?>>Gudang 9</option>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['lokasi']) ? $errorMessages['lokasi'] : '' ?>
                    </td>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>

<table class="content">
    <thead>
        <tr>
            <th rowspan=0>時 間<br />Waktu</th>
            <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
            <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
            <th rowspan=0>批<br />数<br />量<br />Jumlah<br />Lot</th>
            <th rowspan=0>檢<br />驗<br />數<br />Jumlah<br />Inspeksi</th>
            <th colspan=28>不 良 內 容<br />Konten Kondisi Buruk</th>
            <th colspan=3>生 產 狀 況<br />Kondisi Produksi</th>
            <th rowspan=0>Status</th>
        </tr>
        <tr>
            <th><div>絨<br />布<br />劃<br />傷</div></th>
            <th class="rotate"><div>Kain Tergores</div></th>
            <th><div>抽<br >斗<br >配<br >套</div></th>
            <th class="rotate"><div>Tidak Presisi</div></th>
            <th><div>孔<br />位<br />不<br />對</div></th>
            <th class="rotate"><div>Salah Posisi Lubang</div></th>
            <th><div>尺<br />寸<br />不<br />對</div></th>
            <th class="rotate"><div>Salah Ukuran</div></th>
            <th><div>劃<br />傷</div></th>
            <th class="rotate"><div>Tergores</div></th>
            <th><div>溢<br />膠</div></th>
            <th class="rotate"><div>Kelebihan Lem</div></th>
            <th><div>結<br />構<br />鬆<br />動</div></th>
            <th class="rotate"><div>Struktur Longgar</div></th>
            <th><div>崩<br />缺</div></th>
            <th class="rotate"><div>Cover Terpotong</div></th>
            <th><div>開<br />裂</div></th>
            <th class="rotate"><div>Retak</div></th>
            <th><div>砂<br />光<br />不<br />良</div></th>
            <th class="rotate"><div>Sanding Buruk</div></th>
            <th><div>出<br />釘</div></th>
            <th class="rotate"><div>Paku Keluar</div></th>
            <th><div>脫<br />膠</div></th>
            <th class="rotate"><div>Lem Degumming</div></th>
            <th><div>縫<br />隙</div></th>
            <th class="rotate"><div>Gap</div></th>
            <th><div>其<br />他</div></th>
            <th class="rotate"><div>Lainnya</div></th>
            <th><div>缺<br />點<br />數</div></th>
            <th class="rotate"><div>Jumlah Kekurangan</div></th>
            <th>不<br />良<br />數<br /><strong>Jumlah Kualitas Buruk</strong></th>
        </tr>
    </thead>
    <tbody>
        <?php
            if ($data !== null) :
                $dailyInspectionTime = $data->getDailyInspectionTime();
                    if (count($dailyInspectionTime) > 0) :
                        foreach ($dailyInspectionTime as $timeGroup) :
                            $timeGroupRowSpan = count($timeGroup->getDailyInspectionItem()) + 1;
        ?>
        <tr>
            <td rowspan=<?php echo $timeGroupRowSpan; ?>><?php echo $timeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
        </tr>
        <?php
            foreach ($timeGroup->getDailyInspectionItem() as $item) :
                $status = $this->inspectionStatusHelper->getInspectionStatus($item);
        ?>
        <tr>
            <td><?php echo $item->getKodeProduk() ?></td>
            <td><?php echo $item->getNamaProduk() ?></td>
            <td style="text-align:right;"><?php echo $item->getJumlahLot() ?></td>
            <td style="text-align:right;"><?php echo $item->getJumlahInspeksi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemKainTergores() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemTidakPresisi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemSalahPosisiLubang() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemSalahUkuran() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemTergores() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemKelebihanLem() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemStrukturLonggar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemCoverTerpotong() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemRetak() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemSandingBuruk() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemPakuKeluar() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemLemDegumming() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemGap() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemBurukLainnya() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $item->getJumlahItemKekurangan() ?></td>
            <td style="text-align:right;"><?php echo $item->getJumlahTotalItemBuruk() ?></td>
            <td style="text-align:center;color:<?php echo $status ? 'green' : 'red' ?>"><?php echo $status ? 'pass' : 'fail' ?></td>
        </tr>
        <?php
                        endforeach;
                    endforeach;
                endif;
            else :
        ?>
        <tr>
            <td colspan=0 style="text-align:center;">Data kosong!</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php if ($data !== null) : ?>
<input
    type="button"
    value="Print"
    onclick="javascript:window.location.href='<?php
        echo $this->routeManager->generateRoute(array(
            'action' => 'report_general_inspection_single_record_print',
            'key' => $data->getId(),
            'print' => true
        ));
    ?>'">
<?php endif; ?>
<style type="text/css">
    fieldset {
        border: 1px solid;
    }

    table.content thead tr:first-child {
        height: 30px;
    }

    table.content thead tr:last-child {
        height: 120px;
    }

    table.content thead tr th.rotate {
        padding: 0;
        white-space: nowrap;
    }

    table.content thead tr th.rotate > div {
        transform:
            translate(0, 40px)
            rotate(270deg);
        width: 30px;
    }

    table.content tbody td {
        vertical-align: top;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $("#tanggal").datepicker({
            dateFormat: 'dd/mm/yy',
            yearRange: '-55:-0'
        });
    });
</script>
