<h3>Report General Inspection - Pembahanan Kayu</h3>
<?php
    if (!empty($errorMessages)) {
        echo '<div class="error-head">Form yang anda kirim tidak valid.<br />Mohon dicek kembali.<br /></div>';
    }
?>
<hr />
<form action="" method="post">
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>日 期 Tanggal Inspeksi</td>
                <td>
                    <input type="text" required id="tanggal" class="medium" name="tanggal" value="<?php echo $params['tanggal'] ?>">
                    <div class="error-container">
                        <?php echo isset($errorMessages['tanggal']) ? $errorMessages['tanggal'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>定 位 點 Lokasi</td>
                <td>
                    <select id="lokasi" name="lokasi">
                        <option value="">[ 选 一 项 pilih satu ]</option>
                        <option value="Line 1"<?php echo $params['lokasi'] == 'Line 1' ? ' selected' : '' ?>>Line 1</option>
                        <option value="Line 2"<?php echo $params['lokasi'] == 'Line 2' ? ' selected' : '' ?>>Line 2</option>
                        <option value="Line 3"<?php echo $params['lokasi'] == 'Line 3' ? ' selected' : '' ?>>Line 3</option>
                        <option value="Line 4"<?php echo $params['lokasi'] == 'Line 4' ? ' selected' : '' ?>>Line 4</option>
                        <option value="Line 5"<?php echo $params['lokasi'] == 'Line 5' ? ' selected' : '' ?>>Line 5</option>
                        <option value="Line 6"<?php echo $params['lokasi'] == 'Line 6' ? ' selected' : '' ?>>Line 6</option>
                        <option value="Line 7"<?php echo $params['lokasi'] == 'Line 7' ? ' selected' : '' ?>>Line 7</option>
                        <option value="Line 8"<?php echo $params['lokasi'] == 'Line 8' ? ' selected' : '' ?>>Line 8</option>
                        <option value="Line 9"<?php echo $params['lokasi'] == 'Line 9' ? ' selected' : '' ?>>Line 9</option>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['lokasi']) ? $errorMessages['lokasi'] : '' ?>
                    </td>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>
<?php
    if ($data !== null) :
        $pembahananKayuInspectionTime = $data->getPembahananKayuInspectionTime();
?>
<table class="content">
    <thead>
        <tr>
            <th rowspan=0 style="width: 40px;">時 間<br />Waktu</th>
            <th rowspan=0>產 品<br />編 號<br />Kode Produk</th>
            <th rowspan=0>產 品<br />名 稱<br />Nama Produk</th>
            <th rowspan=0 style="width:40px;">批<br />数<br />量<br />Jumlah Lot</th>
            <th rowspan=0 style="width:40px;">檢<br />驗<br />數<br />Jumlah Inspeksi</th>
            <th colspan=38>不 良 內 容<br />Konten Kondisi Buruk</th>
            <th colspan=3>生 產 狀 況<br />Kondisi Produksi</th>
        </tr>
        <tr>
            <th><div>死<br />节</div></th>
            <th class="rotate"><div>Mata Pisau</div></th>
            <th><div>树<br />心</div></th>
            <th class="rotate"><div>Hati Kayu</div></th>
            <th><div>虫<br />孔</div></th>
            <th class="rotate"><div>Pin Hole</div></th>
            <th><div>开<br />裂</div></th>
            <th class="rotate"><div>Pecah</div></th>
            <th><div>划<br />伤</div></th>
            <th class="rotate"><div>Retak</div></th>
            <th><div>尺<br />寸<br />偏<br />小</div></th>
            <th class="rotate"><div>Ukuran Kurang</div></th>
            <th><div>尺<br />寸<br />偏<br />大</div></th>
            <th class="rotate"><div>Ukuran Lebih</div></th>
            <th><div>烂<br />／<br />发<br />霉</div></th>
            <th class="rotate"><div>Busuk/Berjamur</div></th>
            <th><div>蓝<br />斑</div></th>
            <th class="rotate"><div>Bluestain</div></th>
            <th><div>压<br />印</div></th>
            <th class="rotate"><div>Bekas Roda</div></th>
            <th><div>跳<br />刀<br />／<br />刀<br />印</div></th>
            <th class="rotate"><div>Bekas Pisau</div></th>
            <th><div>色<br />差</div></th>
            <th class="rotate"><div>Beda Warna</div></th>
            <th><div>弯<br />翘</div></th>
            <th class="rotate"><div>Bengkok</div></th>
            <th><div>拼<br />缝</div></th>
            <th class="rotate"><div>Garis Lem</div></th>
            <th><div>凹<br />陷</div></th>
            <th class="rotate"><div>Gelombang</div></th>
            <th><div>刀<br />型<br />不<br />对</div></th>
            <th class="rotate"><div>Salah Pisau</div></th>
            <th><div>胶<br />水<br />比<br />率<br />不<br />对</div></th>
            <th class="rotate"><div>Lem Tidak Standard</div></th>
            <th><div>濕<br />度<br />太<br />高</div></th>
            <th class="rotate"><div>Suhu Terlalu Tinggi</div></th>
            <th><div>其<br />它</div></th>
            <th class="rotate"><div>Lainnya</div></th>
            <th>不<br />良<br />數<br />Jumlah Kualitas Buruk</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($pembahananKayuInspectionTime as $pembahananKayuTimeGroup) :
                $pembahananKayuTimeGroupRowSpan = count($pembahananKayuTimeGroup->getPembahananKayuInspectionItem()) + 1;
        ?>
        <tr>
            <td rowspan=<?php echo $pembahananKayuTimeGroupRowSpan; ?>><?php echo $pembahananKayuTimeGroup->getWaktuInspeksi()->format('H:i:s'); ?></td>
        </tr>
        <?php foreach ($pembahananKayuTimeGroup->getPembahananKayuInspectionItem() as $pembahananKayuItem) : ?>
        <tr>
            <td><?php echo $pembahananKayuItem->getKodeProduk() ?></td>
            <td><?php echo $pembahananKayuItem->getNamaProduk() ?></td>
            <td style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahLot() ?></td>
            <td style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahInspeksi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemMataKayuMati() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemHatiKayu() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemPinHole() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemPecah() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemRetak() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemUkuranKurang() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemUkuranLebih() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBusukBerjamur() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBlueStain() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBekasRoda() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBekasPisau() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBedaWarna() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBengkok() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemGarisLem() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemGelombang() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemSalahPisau() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemLemTidakStandard() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemSuhuTerlaluTinggi() ?></td>
            <td colspan=2 style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahItemBurukLainnya() ?></td>
            <td style="text-align:right;"><?php echo $pembahananKayuItem->getJumlahTotalItemBuruk() ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
    <?php endforeach; ?>
</table>
<input
    type="button"
    value="Print"
    onclick="javascript:window.location.href='<?php
        echo $this->routeManager->generateRoute(array(
            'action' => 'report_general_inspection_pembahanan_kayu_print',
            'key' => $data->getId(),
            'print' => true
        ));
    ?>'">
<?php else: ?>
<div style="text-align:center;"><h3>Data tidak ditemukan!</h3></div>
<?php endif; ?>
<style type="text/css">
    fieldset {
        border: 1px solid;
    }

    table.content thead tr:first-child {
        height: 30px;
    }

    table.content thead tr:last-child {
        height: 120px;
    }

    table.content thead tr th.rotate {
        padding: 0;
        white-space: nowrap;
    }

    table.content thead tr th.rotate > div {
        transform:
            translate(0, 40px)
            rotate(270deg);
        width: 30px;
    }

    table.content tbody td {
        vertical-align: top;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $("#tanggal").datepicker({
            dateFormat: 'dd/mm/yy',
            yearRange: '-55:-0'
        });
    });
</script>
