<h3>Delete Monthly Payroll</h3>
<?php
    if (! empty($errorMessages)) {
        echo '<div class="error-head">'
            . 'Form yang anda kirim tidak valid.<br />Mohon dicek kembali.';

        if (! empty($errorMessages['global'])) {
            echo '<ul>';
            foreach ($errorMessages['global'] as $globalError) {
                echo '<li>' . $globalError . '</li>';
            }
            echo '</ul>';
        }

        echo '</div>';
    }
?>
<hr />
