<h3>Generate Monthly Payroll</h3>
<?php
    if (! empty($errorMessages)) {
        echo '<div class="error-head">'
            . 'Form yang anda kirim tidak valid.<br />Mohon dicek kembali.';

        if (! empty($errorMessages['global'])) {
            echo '<ul>';
            foreach ($errorMessages['global'] as $globalError) {
                echo '<li>' . $globalError . '</li>';
            }
            echo '</ul>';
        }

        echo '</div>';
    }
?>
<hr />
<form action="" method="post">
    <?php if ($data == null) : ?>
    <table border="0" width="100%">
        <tbody>
            <tr>
                <td>Bulan</td>
                <td>
                    <select name="month">
                        <?php
                            $monthList = array(
                                '[ pilih satu ]',
                                'Januari',
                                'Februari',
                                'Maret',
                                'April',
                                'Mei',
                                'Juni',
                                'Juli',
                                'Agustus',
                                'September',
                                'Oktober',
                                'November',
                                'Desember'
                            );

                            foreach ($monthList as $key => $value) {
                                if ($key == 0) {
                                    $key = '';
                                } elseif ($key > 0 && $key <= 9) {
                                    $key = '0' . $key;
                                }

                                echo '<option value="' . $key . '"' . ($params['month'] == $key ? ' selected' : '') . '>' . $value . '</option>';
                            }
                        ?>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['month']) ? $errorMessages['month'] : '' ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Tahun</td>
                <td>
                    <select name="year">
                        <?php
                            $now = new \DateTime();
                            $currentYear = $now->format('Y');

                            echo '<option value="">[ pilih satu ]</option>';
                            for ($i = 10; $i > 0; $i--) {
                                echo '<option value="' . $currentYear . '"' . ($params['year'] == $currentYear ? ' selected' : '') . '>' . $currentYear . '</option>';
                                $currentYear--;
                            }
                        ?>
                    </select>
                    <div class="error-container">
                        <?php echo isset($errorMessages['year']) ? $errorMessages['year'] : '' ?>
                    </td>
                </td>
            </tr>
            <tr>
                <td>Company</td>
                <td>
                    <select name="company">
                        <option value="" <?php echo (empty($params['company'])) ? ' selected' : '' ?>>[ semua ]</option>
                        <option value="wwii" <?php echo (strtoupper($params['company'])) == 'WWII' ? ' selected' : '' ?>>WWII</option>
                        <option value="smk" <?php echo (strtoupper($params['company'])) == 'SMK' ? ' selected' : '' ?>>SMK</option>
                        <option value="ics" <?php echo (strtoupper($params['company'])) == 'ICS' ? ' selected' : '' ?>>ICS</option>
                        <option value="skcm" <?php echo (strtoupper($params['company'])) == 'SKCM' ? ' selected' : '' ?>>SKCM</option>
                        <option value="ppc" <?php echo (strtoupper($params['company'])) == 'PPC' ? ' selected' : '' ?>>PPC</option>
                    </select>
                </td>
            </tr>
        </tbody>
    </table>
    <hr />
    <input type="submit" value="Proses" name="btx" />
    <input type="submit" value="Batal" name="btx" />
    <?php else: ?>
    <input type="submit" value="Simpan" name="btx" />
    <input type="submit" value="Reset" name="btx" />
</form>
<table class="content">
    <tr>
        <th rowspan=2>NIK</th>
        <th rowspan=2>Nama</th>
        <th rowspan=2>Departemen</th>
        <th rowspan=2>Status</th>
        <th rowspan=2>Periode Awal</th>
        <th rowspan=2>Periode Akhir</th>
        <th colspan=6>Detail Hari Kerja</th>
        <th rowspan=2>Rincian</th>
    </tr>
    <tr>
        <th>Hadir</th>
        <th>Ijin /<br />Mangkir</th>
        <th>Cuti</th>
        <th>Sakit</th>
        <th>Hari Libur</th>
        <th>Jam Kerja</th>
    </tr>
    <?php foreach ($data as $report) : ?>
    <tr>
        <td><?php echo $report['fCode'] ?></td>
        <td class="nowrap"><?php echo $report['fName'] ?></td>
        <td class="nowrap"><?php echo $report['fDeptName'] ?></td>
        <td style="text-align:center;"><?php echo $report['fStatus'] ?></td>
        <td style="text-align:center;"><?php echo $report['fPeriodeAwal'] ?></td>
        <td style="text-align:center;"><?php echo $report['fPeriodeAkhir'] ?></td>
        <td style="text-align:right;"><?php echo $report['fJumlahKehadiran'] ?></td>
        <td style="text-align:right;"><?php echo $report['fJumlahAbsen'] ?></td>
        <td style="text-align:right;"><?php echo $report['fJumlahCuti'] ?></td>
        <td style="text-align:right;"><?php echo $report['fJumlahSakit'] ?></td>
        <td style="text-align:right;"><?php echo $report['fJumlahHariLibur'] ?></td>
        <td style="text-align:right;"><?php echo $report['fJumlahJamKerjaUser'] ?></td>
        <td class="nowrap" style="text-align:center;">
            <a href="<?php echo $this->routeManager->generateRoute(array(
                'action' => 'edit_jam_kerja_karyawan',
                'key' => "fCode:{$report['fCode']};date:{$params['year']}-{$params['month']}-01"
            )) ?>">edit jam kerja</a>
        </td>
    </tr>
    <?php endforeach; endif; ?>
</table>
<style type="text/css">
    .nowrap {
        white-space:nowrap;
    }
</style>
